export const CONSTANTS = {
    INITIAL_ASTEROIDS_COUNT: 8,
    GAME_REFRESH_TIME: 200,
    GUN_REFRESHING_RATE: 20,
    BULLET_LIFE_SPAN: 100,
    BULLET_LENGTH: 8,
    ASTEROID_MAXSPEED: 1.6,
    ASTEROID_MINSPEED: 0.5,

    SCORE_COUNT: {
        LEVEL_UP: 500,
        BURST: 150,
        HIT: 50
    },

    REFRESH_TIME: 500
};
